# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20181025_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candy_type', models.CharField(max_length=255)),
                ('candy_flavor', models.CharField(max_length=255)),
                ('candy_color', models.CharField(max_length=255)),
                ('themes', models.CharField(max_length=255)),
                ('brands', models.CharField(max_length=255)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_by_user', to='login.User')),
            ],
        ),
    ]
